# -*- coding: utf-8 -*-
"""2022-01-24_Python_BlackJack.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HGBY9KRc2NksRRoHtNWrUkLbEVZgrJUt
"""

from random import shuffle
from random import randrange


def pick_card (person, cards):
  global removed_cards
  i=0
  while i < cards:
    if person == "dealer":
      dealer_hand.append(deck.pop(randrange(51-removed_cards)))
    if person == "player":
      player_hand.append(deck.pop(randrange(51-removed_cards)))
    i+=1
    removed_cards += 1
    

def count (hand, counter):
  y = 0
  while y < len(hand):
    card = hand[y]
    handsplit = card.split(None)
    counter += values[handsplit[0]]
    y+=1
  return counter

def game(player_count):
  global player_hand
  action = input("Do you want to hit another card (h) or to stand (s)?")
  if action == "h":
    player_count = 0
    pick_card("player", 1)
    player_count = count(player_hand, player_count)
    if player_count > 21:
      if 'Ace Heart' in player_hand or 'Ace Diamond' in player_hand or 'Ace Spade' in player_hand or 'Ace Club' in player_hand:
        values['Ace'] = 1
        player_count = 0
        player_count = count(player_hand, player_count)
    print("The Players hand is now", player_hand, "which makes it to", player_count)
    if player_count > 21:
        print("You are now over 21")
        playergame = False
    if player_count < 21:
      playergame = True
    if player_count == 21:
      print("Blackjack!")
      playergame = False
  if action == "s":
    print("So the Players stands with the hand", player_hand, "and a total of", player_count)
    playergame = False
  return player_count, playergame

def dealer(dealer_count, dealer_hand):
  if dealer_count < 17:
    print("As the rules say, i have to hit a new card until the score is above 16")
    pick_card("dealer", 1)
    dealer_count = 0
    dealer_count = count(dealer_hand, dealer_count)
    if dealer_count > 21:
      if 'Ace Heart' in dealer_hand or 'Ace Diamond' in dealer_hand or 'Ace Spade' in dealer_hand or 'Ace Club' in dealer_hand:
        values['Ace'] = 1
        dealer_count = 0
        dealer_count = count(dealer_hand, dealer_count) 
    print("The hand is now", dealer_hand, "which makes it to", dealer_count)
    dealergame = True
    if dealer_count > 21:
      print("So it is above 21")
      dealergame = False  
  if dealer_count > 16 and dealer_count < 21:
    print("So the score is", dealer_count)
    dealergame = False
  if dealer_count == 21:
    print("Blackjack for the Dealer!")
    dealergame = False
  return dealer_count, dealergame
  


gameon = True
while gameon == True:

  input("Type something to start the game")



  deck=[]
  dealer_hand=[]
  player_hand=[]
  player_count = 0
  dealer_count = 0
  removed_cards = 0
  playergame = True
  

  suits = ['Heart', 'Club', 'Spade', 'Diamond']
  ranks = ['Two', 'Three', 'Four', 'Five', 'Six', 'Seven', 'Eight', 'Nine', 'Ten', 'Jack', 'Queen', 'King', 'Ace']
  values = {'Two':2, 'Three':3, 'Four':4, 'Five':5, 'Six':6, 'Seven':7, 'Eight':8, 'Nine':9, 'Ten':10, 'Jack':10, 'Queen':10, 'King':10, 'Ace':11}

  for s in suits:
    for r in ranks:
      deck.append(r + ' ' + s)

  shuffle(deck)

  print("The deck is shuffled and ready. Here are your first two cards")
  pick_card("dealer", 2)
  pick_card("player", 2)

  player_count = count(player_hand, player_count)
  print("The Players hand is", player_hand, "which makes it to", player_count)
  if player_count == 21:
    print("Blackjack!")
    playergame = False
  print("The Dealer card is", dealer_hand[0])

 
  while playergame == True:
    player_count, playergame = game(player_count)

  dealer_count = count(dealer_hand, dealer_count)
  print("So now its the turn of the dealer. The second card is", dealer_hand[1], "and as the first was", dealer_hand[0], "the score is", dealer_count)

  dealergame = True
  while dealergame == True:
    dealer_count, dealergame = dealer(dealer_count,dealer_hand)

  if dealergame == False:
    if player_count > 21:
      print("Your value is", player_count, "so you lost this game.")
    if player_count == 21:
      print("Blackjack for you with a Total of", player_count, ".")
      if player_count == dealer_count:
        print("But the Dealer has also a Blackjack, which makes it to a tie")
      else:
        print("You win!")
    if player_count < 21:
      if player_count > dealer_count:
        print("Your value of", player_count, "is closer to 21 than the value of the dealer", dealer_count, "so you win!") 
      if player_count < dealer_count and dealer_count < 22:
        print("The Dealer count of", dealer_count, "is closer to 21 than yout count of", player_count, "so you loose.")
      if player_count == dealer_count:
        print("It is even with a dealer count of", dealer_count, "and your count as well", player_count, "so you neither loose or win.")
      if player_count < 22 and dealer_count > 21:
        print("The dealer count", dealer_count, "is over 21 so you win with your hand", player_count)




  x = input("Do you want to play again? Y for Yes an N for No")
  while x is not 'N' and x is not 'Y':
    x = input("Sorry i did not understand you. Would you please type in Y for Yes or N for No?")
  if x == 'N':
    gameon = False
  if x == 'Y':
    gameon = True